Update .cicd

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,6 +16,7 @@ defaults:
   run:
     working-directory: "de-it-krachten/ansible-role-olam"
 
+
 jobs:
 
   lint:
@@ -31,6 +32,7 @@ jobs:
         uses: actions/setup-python@v2
         with:
           python-version: '3.x'
+
 
       - name: Show runner info
         run: |
@@ -54,12 +56,15 @@ jobs:
   molecule:
     name: Molecule
     runs-on: ubuntu-latest
+    # continue-on-error: ${{ matrix.continue_on_error }}
     strategy:
-      fail-fast: true
+      fail-fast: false
       matrix:
         include:
           - distro: oraclelinux8
             playbook: converge.yml
+            # continue_on_error: false
+            # failfast: true
 
     steps:
       - name: Check out the codebase.
@@ -71,6 +76,7 @@ jobs:
         uses: actions/setup-python@v2
         with:
           python-version: '3.x'
+
 
       - name: Show runner info
         run: |
@@ -89,20 +95,25 @@ jobs:
         run: |
           sudo modprobe ip6table_filter
 
-      - name: Create molecule.yml from template
+      - name: Retrieve wrapper molecule scripts
         run: |
-          if [[ -f molecule/default/molecule.yml.j2 ]]
-          then
-            export MOLECULE_DISTROS="json:[\"$MOLECULE_DISTRO\"]"
-            e2j2 -f molecule/default/molecule.yml.j2 || exit 1
-          fi
-        env:
-          MOLECULE_DISTRO: ${{ matrix.distro }}
+          set -e
+          sudo apt install curl
+          sudo curl -s -o /usr/local/bin/ansible-galaxy.sh \
+            https://raw.githubusercontent.com/de-it-krachten/ansible-role-molecule/dev/files/ansible-galaxy.sh
+          sudo curl -s -o /usr/local/bin/ansible-requirements-clean.sh \
+            https://raw.githubusercontent.com/de-it-krachten/ansible-role-molecule/dev/files/ansible-requirements-clean.sh
+          sudo curl -s -o /usr/local/bin/molecule-test.sh \
+            https://raw.githubusercontent.com/de-it-krachten/ansible-role-molecule/dev/files/molecule-test.sh
+          sudo chmod 755 /usr/local/bin/ansible-galaxy.sh
+          sudo chmod 755 /usr/local/bin/ansible-requirements-clean.sh
+          sudo chmod 755 /usr/local/bin/molecule-test.sh
 
       - name: Run Molecule tests.
-        run: molecule test
+        run: molecule-test.sh
         env:
           PY_COLORS: '1'
           ANSIBLE_FORCE_COLOR: '1'
           MOLECULE_DISTRO: ${{ matrix.distro }}
           MOLECULE_PLAYBOOK: ${{ matrix.playbook }}
+
